# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-29 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0002_auto_20200929_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('customer', models.CharField(blank=True, max_length=50, null=True)),
                ('fee', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('refunded', models.NullBooleanField()),
                ('livemode', models.NullBooleanField()),
                ('currency', models.CharField(blank=True, max_length=5, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('paid', models.NullBooleanField()),
                ('token', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=5, null=True)),
                ('cvc_check', models.CharField(blank=True, max_length=5, null=True)),
                ('exp_month', models.IntegerField(blank=True, null=True)),
                ('exp_year', models.IntegerField(blank=True, null=True)),
                ('last4', models.CharField(blank=True, max_length=4, null=True)),
                ('card_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StripeVariant',
            fields=[
                ('paymentvariant_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='payment.PaymentVariant')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('stripe_card_id', models.CharField(blank=True, max_length=50, null=True)),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stripe_provider.StripeReceipt')),
            ],
            options={
                'abstract': False,
            },
            bases=('payment.paymentvariant',),
        ),
    ]
