name: Run tests

on:
  push:
    branches: [ '*' ]
    tags: [ '*' ]

jobs:
  build:
    name: Python ${{ matrix.python-version }}, Django ${{ matrix.django-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - python-version: '2.7'
            django-version: '1.11'
            requirements-file: requirements-test.py2.txt
          - python-version: '3.7'
            django-version: '1.11'
            requirements-file: requirements-test.py3.txt
          - python-version: '3.8'
            django-version: '2.0'
            requirements-file: requirements-test.py3.txt
            coverage: true
          - python-version: '3.8'
            django-version: '3.0'
            requirements-file: requirements-test.py3.txt

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Install dependencies & project
        run: |
          pip install Django~=${{ matrix.django-version }}
          pip install -r ${{ matrix.requirements-file }}

      - name: Create test database
        run: python ${GITHUB_WORKSPACE}/satchless_test/manage.py migrate

      - name: Run tests
        env:
          COVERAGE: ${{ matrix.coverage }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: ./run-tests.sh
