name: Run tests

on:
  push:
    branches: [ '*' ]
    tags: [ '*' ]

jobs:
  build:
    name: Python ${{ matrix.python-version }}, Django ${{ matrix.django-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - python-version: '2.7'
            django-version: '1.11'
          - python-version: '3.7'
            django-version: '1.11'
          - python-version: '3.8'
            django-version: '2.0'

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Install dependencies & project
        run: |
          pip install Django~=${{ matrix.django-version }}
          pip install -r requirements-test.txt

      - name: Create test database
        run: python ${GITHUB_WORKSPACE}/satchless_test/manage.py migrate

      - name: Run tests
        shell: bash
        run: |
          # Discover satchless apps with tests
          apps_with_test_dirs=( $(find . | grep tests/__init__.py | sed 's/\/tests\/__init__\.py//g' | sed 's/\//./g' | sed 's/^\.\.//g') )
          apps_with_test_py=( $(find . | grep 'test[a-z_0-9].py' | sed 's/\/test.*py//g' | sed 's/\//./g' | sed 's/^\.\.//g') )
          apps_to_test=( "${apps_with_test_dirs[@]}" "${apps_with_test_py[@]}" )
          # Run them
          python ${GITHUB_WORKSPACE}/satchless_test/manage.py test ${apps_to_test[@]}
