name: Run tests

on:
  push:
    branches: [ '*' ]
    tags: [ '*' ]

jobs:
  build:
    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - python-version: 2.7.18
          - python-version: 3.8.6

    steps:
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Run tests
        env:
          DJANGO_SETTINGS_MODULE: tests.settings
        run: |
          python setup.py install
          python ./tests/runtests.py
